### ISSUE TITLE
Upload a Java Tutorial.

### ISSUE THREAD

**Issue by nlanson** [Zilleyy/360Lib#1]
Hello, I would like to raise a concern that many people, including myself, cannot code in Java. 

This can be resolved if you can upload a Java tutorial.

**Comment by Zilleyy** [comment]
pull request merged to master.

**Comment by nlanson** [comment]
i would like to raise to your attention that this was actually not a pull request.

**Comment by Zilleyy** [comment]
Thank you for the clarification.

**Comment by nlanson** [comment]
Issue resolved and closed.
